# AUTO BUILDS #
# From https://github.com/Poeschl/Hassio-Addons
# name: slug/filename ; could be slug/config.* for all files
adsb-multi-portal-mqtt-sensors-adsbfi: adsb-multi-portal-mqtt-sensors-adsbfi/config.* # Image : yes
adsb-multi-portal-mqtt-sensors-adsbx: adsb-multi-portal-mqtt-sensors-adsbx/config.* # Image : yes
adsb-multi-portal-mqtt-sensors-fr24: adsb-multi-portal-mqtt-sensors-fr24/config.* # Image : yes
adsb-multi-portal-mqtt-sensors-opensky: adsb-multi-portal-mqtt-sensors-opensky/config.* # Image : yes
